### PR TITLE
Resolve __ENABLE_TRACES__ correctly (#95)

### LINKED ISSUE #95: APM produces warnings when disabled by the environment variable
**Expected behavior**
No logs

**Actual  behavior**
Looks like APM tries to connect to the agent. The following log message appears every 5 minutes
```java
[dd.trace 2023-07-28 15:27:36:235 +0000] [dd-trace-processor] WARN datadog.trace.agent.common.writer.ddagent.DDAgentApi - Error while sending 1 (size=3KB) traces. Total: 8967, Received: 8967, Sent: 0, Failed: 8967. java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8126 (Will not log errors for 5 minutes)
````

**Environment variables**
```json
{
          "name": "DD_ENV",
          "value": "stage"
        },
        {
          "name": "DD_SERVICE",
          "value": "instance"
        },
        {
          "name": "DD_LOGS_INJECTION",
          "value": "true"
        },
        {
          "name": "DD_TRACE_ENABLED",
          "value": "false"
        },
        {
          "name": "DD_APPSEC_ENABLED",
          "value": "false"
        },
        {
          "name": "DD_VERSION",
          "value": "%APP_VERSION%"
        }
```

**build.sbt**
```scala
datadogApmVersion := Common.datadogVersion
datadogServiceName := "${DD_SERVICE}"
datadogAgentTraceUrl := TraceAgentUrl.defaultHttpUrl
datadogProfilingEnabled := false
datadogAllocationProfilingEnabled := false
```

**Versions**
datadog APM "1.16.0"
"com.guizmaii" % "sbt-datadog" % "4.9.3"

**Configuration log message**
```java
[dd.trace 2023-07-28 16:08:10:662 +0000] [dd-task-scheduler] INFO datadog.trace.agent.core.StatusLogger - DATADOG TRACER CONFIGURATION {"version":"1.16.0~0226e41db3","os_name":"Linux","os_version":"5.10.184-175.731.amzn2.x86_64","architecture":"amd64","lang":"jvm","lang_version":"11.0.20","jvm_vendor":"Amazon.com Inc.","jvm_version":"11.0.20+8-LTS","java_class_version":"55.0","http_nonProxyHosts":"null","http_proxyHost":"null","enabled":true,"service":"instance","agent_url":"http://localhost:8126","agent_error":true,"debug":false,"trace_propagation_style_extract":["datadog"],"trace_propagation_style_inject":["datadog"],"analytics_enabled":false,"sampling_rules":[{},{}],"priority_sampling_enabled":true,"logs_correlation_enabled":true,"profiling_enabled":false,"remote_config_enabled":true,"debugger_enabled":false,"appsec_enabled":"FULLY_DISABLED","telemetry_enabled":true,"dd_version":"2023.07.28-18.28","health_checks_enabled":true,"configuration_file":"no config file present","runtime_id":"9b658c3e-b13f-4720-931f-284422c921de","logging_settings":{"levelInBrackets":false,"dateTimeFormat":"'[dd.trace 'yyyy-MM-dd HH:mm:ss:SSS Z']'","logFile":"System.err","configurationFile":"simplelogger.properties","showShortLogName":false,"showDateTime":true,"showLogName":true,"showThreadName":true,"defaultLogLevel":"INFO","warnLevelString":"WARN","embedException":false},"cws_enabled":false,"cws_tls_refresh":5000,"datadog_profiler_enabled":true,"datadog_profiler_safe":true}
```

### PR DESCRIPTION
**Pull request by Captain1653**
Fixes #95

### CODE REVIEW

**Comment by Captain1653** [comment]
Build failed because `sbt` tried to resolve `sbt-native-packager` version 2.13.1.0 , becase `scalaVersion=2.13.12`. If I change `scalaVersion=2.12.17` then everything works fine.
Screenshot 2023-10-20 at 18 43 41

**Comment by Captain1653** [comment]
@guizmaii  Can it be reviewed ?) Please

**Comment by alok1111** [comment]
Hi @guizmaii. The PR is open for 2 weeks. Can we get any response?

**Comment by alok1111** [comment]
We already tested this change in our environment, and it fixes the issue.

**Comment by guizmaii** [comment]
Hey @Captain1653 @alok1111,

Sorry for the late reply.

In the doc, I say this:
> Note that if you have the DD_TRACE_ENABLED environment variable set, it'll take precedence over this setting.
image

AFAIU, with your change, this will not be true anymore.
The current code is also probably incorrect as indeed if the `DD_TRACE_ENABLED` is set to `false` then it fallbacks to the `datadogApmEnabled` value, which also doesn't respect the documentation.

The correct fix seems to be to check if the `DD_TRACE_ENABLED` envvar exists,
if it does, just use its value
if it doesn't, use `datadogApmEnabled` value

No? 🤔

**Comment by guizmaii** [comment]
See https://github.com/guizmaii/sbt-datadog/pull/109

**Comment by guizmaii** [comment]
@Captain1653 @alok1111 I release a new version containing my fix: https://github.com/guizmaii/sbt-datadog/releases/tag/v4.9.4

Please let me know if it works for you.
Feel free to re-open this PR if it doesn't 🙂

**Comment by alok1111** [comment]
@guizmaii Looks like your fix breaks the `DD_TRACE_ENABLED` env variable usage.
I think you misplaced the root then/else branches. Currently, if there is no variable, it tries to parse it. Execution stops with the following message: `Invalid value for DD_TRACE_ENABLED: . Must be  or `. There is also some message formatting issue.
If there is a variable, the logic takes the default.

**Pull request closed without merging**
